# Region to chainId which is the first two characters in address mapping. This is used
# to shard the blockchain so that transactions between the same region will be inner
# chain and transaction between regions will be the inter chain which costs more.
---
Africa: '0002'
Asia: '0001'
Americas: '0000'
Europe: '0002'
Oceania: '0001'
